[mypy]
# Força a tipagem de funções. Se não tipar os argumentos ou o retorno, gera erro.
disallow_untyped_defs = True

# Impede que você chame funções não tipadas de dentro de funções tipadas
disallow_incomplete_defs = True

# Avisa quando você está tentando usar um retorno que foi definido como 'Any'
warn_return_any = True

# Mostra códigos de erro específicos no terminal para facilitar a correção
show_error_codes = True

# Ignora falta de tipagem em bibliotecas externas de terceiros que não possuem type hints
ignore_missing_imports = True